### ISSUE TITLE
the problem about TransformerEncoder module

### ISSUE THREAD

**Issue by 18370029656** [dengyecode/hourglassattention#2]
Hello, after reading your code, I found that line 37, transE1(), can use both mask and feature as inputs. What would be the difference in the results with or without mask input transE1()? Looking forward to your reply!
您好，在看完您的代码之后，发现第37行transE1()可以将mask和feature同时作为输入。请问在有无mask输入transE1()的情况下，结果将会有什么区别呢？期待您的回答！
<img width="680" alt="image" src="https://user-images.githubusercontent.com/108872700/233949402-0ef1f644-c190-401d-96cf-ef741b4cc962.png">

**Comment by dengyecode** [comment]
In image inpainting, training with a mask as input enables the model to identify the damaged area of the image, resulting in better performance compared to models trained without a mask.
在图像补全中，包含mask作为输入的训练使得模型能够确认图像的破损位置，从而性能往往会比不含有mask的模型高一些

**Comment by 18370029656** [comment]
Hello, the source code uses line 37. May I ask if replacing line 37 with line 38, which means entering both feature and mask simultaneously, would it have any impact? Because I saw that there is an if statement about the mask in the attention mechanism later.
您好，源代码中使用的是第37行，我想请问如果用第38行代替37行，即同时输入feature和mask，会有什么影响吗？因为我看后面注意力机制中有关于mask的if判断语句。
![image](https://user-images.githubusercontent.com/108872700/234011311-fedcdb8d-5c1b-42d8-8137-3a63c454c800.png)
![1](https://user-images.githubusercontent.com/108872700/234012121-8fba6cfd-5ce2-4539-a025-a610ea6bf57c.png)

**Comment by dengyecode** [comment]
Of course, you can use it. My previous experimental results showed that the mask had little impact on performance, so I did not use it. By the way, when using a mask, please remember to resize the mask to the same resolution as the “feature” (same "height" and "width").
当然，你可以使用。不过在我之前的实验结果表明掩膜对性能影响不大，因此我们没有使用。此外，当你使用掩膜时，请记得把掩膜resize为和特征同样的分辨率(同样的高与宽度)。

**Comment by Sheeran2000** [comment]
> 您好，源代码使用了第37行，请问如果将第37行替换为第38行，即同时输入feature和mask，会有什么影响吗？因为我后面看到注意机制中有一个关于mask的if语句。 您好，源代码中使用的是第37行，我想问如果用第38行代替37行，即同时输入feature和mask，有什么影响吗？因为我看后面的注意力机制集中在关于mask的if判断语句。 ![图像](https://user-images.githubusercontent.com/108872700/234011311-fedcdb8d-5c1b-42d8-8137-3a63c454c800.png) ![1](https://user-images.githubusercontent.com/108872700/234012121-8fba6cfd-5ce2-4539-a025-a610ea6bf57c.png)

你好，你完整复现出来了吗 结果相差大吗
