### ISSUE TITLE
test.py

### ISSUE THREAD

**Issue by 18370029656** [dengyecode/hourglassattention#3]
Hello, may I ask how to load the training model for testing in the test.py? Looking forward to your reply！

**Comment by dengyecode** [comment]
Assuming you have already trained a model, there should be a checkpoint folder in your project's root directory. If it does not exist, it will be created. The model you trained will be saved in a subfolder of the checkpoint folder, assuming it is named "Places2". Inside this folder, you will find the "loss_log.txt", "train_opt.txt", a folder for saving images, and the saved training model, "xx.pth". Ensure that the "Places2" folder is in the checkpoints directory. Then, 
modify the "name" to "Places2" in the "base_options.py" file (line 15) located in the "options" folder. Similarly, you need to modify the "batchsize" (set to 1 on line 33), the test folder path (line 25), and the "mask_type" (line 17) you want to use in the "base_options.py" file. If you want to use additional mask files, such as those provided by partial convolution, set the "mask_type" to 3 and input the mask folder location on line 26 ("mask_file"). Finally, you can modify the location of the test output image in the "test_option. py" file on line 9 ("results_dir").

After modifying these options, you can directly test through "python test.py". If you have any problems, just ask me

**Comment by 18370029656** [comment]
May I ask if the imported model is latest.pth? Still 5000_ net_ G.pth？ The following are my trains_ options. py and base_ options.py
请问导入的模型是latest.pth吗？还是5000_net_G.pth？以下分别是我的train_options.py和base_options.py
![QWPYI HMIOVRSSSQ3B$G9JY](https://user-images.githubusercontent.com/108872700/234519062-c750660f-4f5e-40f6-8be7-4a035e5ec4d6.png)
![1](https://user-images.githubusercontent.com/108872700/234521665-3eb5feda-adf4-4788-888a-00c166b6db35.png)

**Comment by 18370029656** [comment]
May I ask if the imported model is latest.pth? Still 5000_ net_ G.pth？ The following are my trains_ options. py
请问导入的模型是latest.pth吗？还是5000_net_G.pth？以下分别是我的train_options.py
![1](https://user-images.githubusercontent.com/108872700/234522101-2b3ced95-29f4-4489-a188-00e2fc30c3e8.png)
![QWPYI HMIOVRSSSQ3B$G9JY](https://user-images.githubusercontent.com/108872700/234522145-039f68c5-fded-471d-a21c-ff5deb97bd77.png)

**Comment by dengyecode** [comment]
是latest，由base_options.py文件中第21号的"which_iter"决定

**Comment by 18370029656** [comment]
ok，thank you for your reply！

**Comment by Sheeran2000** [comment]
你已经复现出来了吗

**Comment by Sheeran2000** [comment]
> 是latest，由base_options.py文件中第21号的"which_iter"决定

您好  为什么我复现出来的指标很差呢 具体需要什么超参数吗
