### ISSUE TITLE
the color is grey?

### ISSUE THREAD

**Issue by cwyyt** [dengyecode/hourglassattention#5]
hello, I train your code, but the color is grey.  the following code is wrong? 
/utils/util
(np.transpose(image_numpy, (1, 2, 0)) + 1) / 2.0

**Comment by dengyecode** [comment]
I have tried to train the code to confirm the color is normal color, is it possible that you run the environment problems? 
I've uploaded my runtime environment in the ``requirements.yaml'' file so you can compare it.
By the way the code you listed it is only for visualization and is not involved in training.

**Comment by cwyyt** [comment]
Thank you!

**Comment by cwyyt** [comment]
> I have tried to train the code to confirm the color is normal color, is it possible that you run the environment problems? I've uploaded my runtime environment in the ``requirements.yaml'' file so you can compare it. By the way the code you listed it is only for visualization and is not involved in train

**Comment by Sheeran2000** [comment]
> 谢谢你！

你好 你完整的复现出来了吗
