### ISSUE TITLE
issue about loss

### ISSUE THREAD

**Issue by 18370029656** [dengyecode/hourglassattention#7]
Hello, I'm sorry to bother you. During the training process, my adversarial loss and discriminator loss remained basically unchanged. What may be the reason? Looking forward to your providing me with a solution, thank you!!
您好，不好意思打扰您了。在训练过程中，我的对抗性损失和鉴别器损失基本都不变化，可能是什么原因呢？期待您能够给我提供解决思路，万分感谢！！
![85%SAFXWJ2OTGO A}ZE%59N](https://user-images.githubusercontent.com/108872700/235394675-af2da878-f1f6-4e96-b2a9-f465e620ae81.png)

**Comment by dengyecode** [comment]
确实是这样的。首先生成对抗损失本身与其它损失不同，需要保持一定的大小的值来对抗才能比较好的训练。 能够由于在训练过程中对抗损失超参数比较小，并且其实不多次数的迭代后网络就能输出含有基本语义的图像。因此变动不会特别大。

**Comment by 18370029656** [comment]
谢谢您的回答！！

**Comment by Sheeran2000** [comment]
> 谢谢您的回答！！

你好 你完整的复现出来了吗
